name = "formate"
main = ".output/server/index.mjs"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]
keep_vars = true
routes = [ { pattern = "formate.app", custom_domain = true } ]

[assets]
binding = "ASSETS"
directory = ".output/public"

[observability.logs]
enabled = false
